### ISSUE TITLE
Request: fine-grained configuration for codec packages for downstream projects

### ISSUE THREAD

**Issue by magicDGS** [broadinstitute/gatk#4180]
The packages for codecs is a key feature for downstream tools implementing new codecs for other formats or to include overrides of codecs already included. Nevertheless, the current implementation (at version 4.0.0.0) the only way of configuring this is at the package level using the `codec_packages` configuration.

I request support for the following fine-grained configuration:

* Add/Remove concrete codec classes
* Exclude single classes from a concrete `codec_package` specified (this can be done by the previous requirement if it uses fully qualified codec names)
* Exclude sub-packages from a concrete `codec_package` specified

Representing this in an YML format, I would like to have the ability to configure the codecs as following:

```yml
- codecs:
    - packages:
        - htsjdk.variant
        - htsjdk.tribble
            - exclude_class: bed.BEDCodec
        - org.broadinstitute.hellbender.utils.codecs
            - exclude_package: gencode
        - org.magicdgs.htsjdk.codecs
    - classes:
        - org.external.htsjdk_codecs.CustomBedCodec
```

This would be even more useful if HTSJDK is moving to an interface-based library...
